apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsql-deployment
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 2  # สำคัญ!
  selector:
    matchLabels:
      app: appsql
  template:
    metadata:
      labels:
        app: appsql
    spec:
      containers:
        - name: appsql
          image: thawatchai95/appsql:sha-688f37dcd1fb911576b78d5cca804375c9d73d78
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: appsql-secret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: appsql-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: appsql-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appsql-secret
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
