apiVersion: apps/v1
kind: Deployment
metadata:
  name: AppSQL-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: AppSQL
  template:
    metadata:
      labels:
        app: AppSQL
    spec:
      containers:
        - name: AppSQL
          image: thawatchai95/appsql
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10