apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: default
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "P@ssw0rd"  # รหัสผ่าน root ของ MySQL
          - name: MYSQL_DATABASE
            value: "mydatabase
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
            subPath: mysql-data
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 5Gi
        storageClassName: longhorn  # ใช้ Longhorn เป็น Storage