apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: default
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mydatabase;
    USE mydatabase;

    CREATE TABLE IF NOT EXISTS users (
      id INT AUTO_INCREMENT PRIMARY KEY,
      username VARCHAR(255) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );