apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  admin.password: "$2y$10$9PS.o57LpqFoRdVoJa3DCeDDxu9BjjSSn3LZVP9EdPQ4kyV5AWr.K"
  admin.passwordMtime: "2026-03-17T07:39:35Z"
