apiVersion: v1
kind: Secret
metadata:
  name: repo-AppSQL
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/thawatchai-rvc/03-Action-AppSQL-CICD.git